language: android
jdk:
  - openjdk7

android:
  components:

    - build-tools-23.0.2
    - android-22

notifications:
  email: true

cache: false

sudo: false

install:

  - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v

