language: android
jdk:
  - openjdk7

android:
  components:
    - build-tools-21.1.2
    - android-21

cache: false

sudo: false

install:

  - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v

script:
  - ./gradlew clean assembleDebug